### ISSUE TITLE
org.freedesktop.Platform branch 22.08 is end-of-life

### ISSUE THREAD

**Issue by baskin77** [flathub/io.enpass.Enpass#8]
io.enpass.Enpass needs freedesktop Platform 22.08. Please take note this branch is end-of-life. Can you update the package to use the latest freedesktop platform?

`Info: runtime org.freedesktop.Platform branch 22.08 is end-of-life, with reason:
   org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   io.enpass.Enpass

Info: runtime org.freedesktop.Platform.VAAPI.Intel branch 22.08 is end-of-life, with reason:
   org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   io.enpass.Enpass

Info: runtime org.freedesktop.Platform.GL.default branch 22.08-extra is end-of-life, with reason:
   org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   io.enpass.Enpass

Info: runtime org.freedesktop.Platform.GL.default branch 22.08 is end-of-life, with reason:
   org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   io.enpass.Enpass
`

**Comment by ShobuPrime** [comment]
Updated! https://github.com/flathub/io.enpass.Enpass/pull/9
